language: go

go:
  - 1.12
  - 1.13
  - 1.x

install:
  - mkdir -p $GOPATH/bin
  - go get -u github.com/go-playground/overalls
  - make deps

script:
  - make test

after_success:
  - $GOPATH/bin/overalls -project=github.com/vgarvardt/rklotz -covermode=count
  - bash <(curl -s https://codecov.io/bash) -f overalls.coverprofile
