name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - created

jobs:

  build:
    strategy:
      matrix:
        go-version: [1.13, 1.14, latest]

    name: Test
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go-version }}
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get test dependencies
        run: make deps

      - name: Run tests
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        if: success()
        with:
          file: ./coverage.txt
          fail_ci_if_error: false

      - name: Build and push release image to the registry
        uses: docker/build-push-action@v1
        if: success() && ${{ matrix.go-version }} == "latest" && ${{ github.event }} == "release"
        with:
          repository: "vgarvardt/rklotz"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: format("version={0}", github.ref)
          tags: format("{0},{1}", github.ref, "latest")
